INFO:root:Executed R('load(\'../../instructor/assignments/hw4/hw4-tests.rda\')')
INFO:root:Executed R('library(plyr)')
INFO:root:Executed R('listLengths.r <- listLengths(test$listLengths)')
ERROR:root:(3 points) Checking R('all.equal(listLengths.r, sol$listLengths)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Modes: logical, numeric
ERROR:root:(1 points) Checking R('all.equal(length(listLengths.r), length(sol$listLengths))')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Mean absolute difference: 5
INFO:root:Executed R('powers.r <- powers(seq(1, 3, by = 1), 3)')
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in result[, 1] = x : object 'result' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in result[, 1] = x : object 'result' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in result[, 1] = x : object 'result' not found

ERROR:root:(3 points) Checking R('all.equal(powers.r, sol$powers, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(powers.r, sol$powers, check.attributes = F) : 
  object 'powers.r' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(powers.r, sol$powers, check.attributes = F) : 
  object 'powers.r' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(powers.r, sol$powers, check.attributes = F) : 
  object 'powers.r' not found

ERROR:root:(1 points) Checking R('all.equal(length(powers.r), length(sol$powers), check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(length(powers.r), length(sol$powers), check.attributes = F) : 
  object 'powers.r' not found

ERROR:root:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(length(powers.r), length(sol$powers), check.attributes = F) : 
  object 'powers.r' not found

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(length(powers.r), length(sol$powers), check.attributes = F) : 
  object 'powers.r' not found

INFO:root:Executed R('recipe.r <- recipeConversion(test$recipe)')
ERROR:root:(3 points) Checking R('all.equal(recipe.r, sol$recipe, check.attributes=F, tolerance=1e1)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Component “amount”: Mean absolute difference: 353.4
INFO:root:Executed R('bootstrapVarEst.r <- bootstrapVarEst(test$bootstrapVarEst.x, test$bootstrapVarEst.B)')
INFO:root:(3 points) R('all.equal(bootstrapVarEst.r, sol$bootstrapVarEst, check.attributes=F, tolerance=1)')[0] is True
INFO:root:Executed R('jackknifeVarEst.r <- jackknifeVarEst(test$jackknifeVarEst.x)')
INFO:root:(3 points) R('all.equal(jackknifeVarEst.r, sol$jackknifeVarEst, check.attributes=F, tolerance=1)')[0] is True
INFO:root:Executed R('samplingVarEst.r <- samplingVarEst(test$samplingVarEst.x, test$samplingVarEst.type)')
INFO:root:(3 points) R('all.equal(samplingVarEst.r, sol$samplingVarEst, check.attributes=F, tolerance=1)')[0] is True
INFO:root:You got a 9 out of 20.
